### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by KeizerDev** [KeizerDev/Rhythmbox-Pleer#1]
@G-S2h, how about a button for saving music to the music folder? Would be awesome!

**Comment by G-S2h** [comment]
Yea it would be cool. I will check this out. (;

**Comment by KeizerDev** [comment]
Cool :+1:

**Comment by KeizerDev** [comment]
Wow, good job! One little bug is that download path doesn't update immediately after changing but good job after all! :+1:

**Comment by G-S2h** [comment]
Ok, it is fixed. But it seems like code is getting a bit messy. Anyway as it's been said in the previous commit, it still needs some corrections.
For instance I may try to set a « Browse... » dialogbox instead of a simple Entry for Download path.
