### ISSUE TITLE
load more results

### ISSUE THREAD

**Issue by Joseph65** [KeizerDev/Rhythmbox-Pleer#3]
the plugin loads 20 song results how to load more

**Comment by G-S2h** [comment]
Right now it's kind of hardcoded but I'm going to work on that in the next day. (;
If you feel like to do it by yourself, check _PleerSearch.py_ and _limit_ parameter in Pleer Browser-Extension API.

**Comment by G-S2h** [comment]
I couldn't find a proper way to set a default value for _Tracks per page_ so it's just hardcoded (20).
